apiVersion: v1
kind: Service
metadata:
  name: cloudsentinel-service
  namespace: cloudsentinel
  labels:
    app.kubernetes.io/name: cloudsentinel
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: cloudsentinel
