apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudsentinel-staging

bases:
  - ../../base

nameSuffix: -staging

commonLabels:
  environment: staging

replicas:
  - name: cloudsentinel-core
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: cloudsentinel-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "INFO"
  - target:
      kind: Deployment
      name: cloudsentinel-core
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "staging"
